language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

before_install:
  - npm install -g electron@1.8.4 orca

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run tox
